### ISSUE TITLE
【FE】マイレシピ詳細ページUI作成

### ISSUE THREAD

**Issue by TomoyaOgashiwa** [qin-team-recipe/12-recipe-app#87]
## リンク

- [Figma のリンク](https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=7778-3881&mode=dev)

## ブランチ

feat/87/create_my_recipe_detail_page

## 概要

<img width="237" alt="スクリーンショット 2023-07-07 19 56 17" src="https://github.com/qin-team-recipe/12-recipe-app/assets/47682517/0dfcbde6-9f30-4534-8f80-790141fc1286">

## 実装 Issue

- [ ] マイレシピ詳細ページUI作成

**Comment by tuboihirokidesu** [comment]
#99 で対応しました
